//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Webbamoscoffe.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Cart_Item
    {
        public int cart_item_id { get; set; }
        public int cart_id { get; set; }
        public int product_id { get; set; }
        public int quantity { get; set; }
        public Nullable<System.DateTime> created_at { get; set; }
        public Nullable<System.DateTime> updated_at { get; set; }
        public Nullable<decimal> price { get; set; }
    
        public virtual Cart Cart { get; set; }
        public virtual Drink Drink { get; set; }
    }
}
